local monitor = peripheral.find("monitor")
monitor.clear()
monitor.setCursorPos(1, 1)

monitor.write("#")
print("start in 5")
os.sleep(1)
monitor.setCursorPos(2, 1)
monitor.write("#")
print("start in 4")
os.sleep(1)
monitor.setCursorPos(3, 1)
monitor.write("#")
print("start in 3")
os.sleep(1)
monitor.setCursorPos(4, 1)
monitor.write("#")
print("start in 2")
os.sleep(1)
monitor.setCursorPos(5, 1)
monitor.write("#")
print("start in 1")
os.sleep(1)
monitor.setCursorPos(1, 2)
monitor.write("Fireworks started")
print("Fireworks started")
redstone.setOutput("top", true)
os.sleep(1)
redstone.setOutput("top", false)